version: "3"
services:
  gifstreamer:
    build: .
    restart: unless-stopped
    network_mode: host
    environment:
      - "LEDSERVER_HOST=127.0.0.1"
      - "LEDSERVER_PORT=20304"
    volumes:
      - .:/app
